### ISSUE TITLE
Commands run in headless child model's command center error silently

### ISSUE THREAD

**Issue by qiemem** [NetLogo/LevelSpace#144] opened 2022-07-16 17:17 UTC
To reproduce: Open a model and run `ls:create-models 1 user-file` to create a child model. Run `ls:show 0` to open a view of that model. Run `error "foo"` in the command center of that model. No error is reported.

**Comment by LaCuneta** [comment] 2022-09-20 20:09
Duplicate of #103

**Closed by LaCuneta** 2022-09-20 20:09 UTC
Labels: duplicate
